repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0 # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: name-tests-test
        args: ["--django"]
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
      - id: check-yaml
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: detect-aws-credentials
      - id: detect-private-key
